import React, { useMemo } from 'react';
import { Image, Spin } from '@arco-design/web-react';

import styles from './index.module.scss';

interface IImageGalleryProps {
  /** 加载状态 */
  loading?: boolean;
  /** 图片尺寸,wxh,如255x256, 512x512, 1024x1024 */
  imgSize?: string;
  /** 图片地址 */
  imgUrl?: string;
}

export default function ImageGallery(props: IImageGalleryProps) {
  const { loading =  false, imgSize = '256x256', imgUrl } = props;

	const imageRect = useMemo(() => {
		const [w, h] = imgSize.split('x');
		return { width: Number(w), height: Number(h) };
	}, [imgSize]);

  return (
    <Spin
      loading={loading}
      tip="Magic is happening..."
      className={styles.spin}
    >
      <Image 
        alt="an image generated by openai"
        className={styles.image}
        style={{
          width: imageRect.width,
          height: imageRect.height
        }}
        src={imgUrl}
        loader={
          <img
            width={imageRect.width}
            src={imgUrl}
            style={{
              filter: 'blur(5px)'
            }}
          />
        }
      />
    </Spin>
  )
}