import { useState } from 'react';
import { Form, Input, Button, Upload, Image, Spin } from '@arco-design/web-react';
import useRequest from '../services/useRequest';
import { apiGenerate } from '../services/api';

import styles from '../styles/index.module.scss';

const FormItem = Form.Item;

const IMAGE_FIELD = 'image';

function handleFormData(formValues) {
	const formData = new FormData();
	for (let [field, value] of Object.entries(formValues)) {
		if (field === IMAGE_FIELD) {
			formData.append(field, value[0]?.originFile);
		} else {
			formData.append(field, value);
		}
	}

	return formData;
}

export default function Home() {
	const [imgUrl, setImgUrl] = useState('');
	const [form] = Form.useForm();

	const {
		loading: submitLoading,
		run: runGenerate
	} = useRequest(apiGenerate, {
		manual: true,
		onSuccess(data) {
			setImgUrl(data.result)
		}
	});

	function onSubmit(event) {
    event.preventDefault();
		const formValues = form.getFields();
    const formData = handleFormData(formValues);
		// 生成图片
		runGenerate({ formData })
  }

	return (
		<div className={styles.pageWrapper}>
			<div className={styles.pageContent}>
				<div className={styles.formWrapper}>
					<Form form={form} disabled={submitLoading}>
						<FormItem
							label="Prompt"
							field="prompt"
							rules={[{ required: true }]}
						>
							<Input
								placeholder="please enter prompt"
							/>
						</FormItem>
						<FormItem
							label="Image"
							field="image"
							triggerPropName="fileList"
						>
							<Upload
								listType="picture-card"
								imagePreview
								name="files"
								limit={1}
								action="/"
							/>
						</FormItem>
						<FormItem wrapperCol={{ offset: 5 }}>
							<Button
								type="primary"
								loading={submitLoading}
								onClick={onSubmit}
							>Generate Image</Button>
						</FormItem>
					</Form>
				</div>
				<div className={styles.imageWrapper}>
					<Spin
						loading={submitLoading}
						tip="Magic is happening..."
						className={styles.spin}
					>
						<Image 
							alt="an image generated by openai"
							className={styles.image}
							src={imgUrl}
							loader={
								<img
									width={256}
									src={imgUrl}
									style={{
										filter: 'blur(5px)'
									}}
								/>
							}
						/>
					</Spin>
				</div>
			</div>
		</div>
	)
}